language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "rondoublec"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Rondoublec_myerp9 -Dsonar.login=c89e6dc40e941900ea9e6099aa31778d31553e2e
  
  
